### ISSUE TITLE
Document user anonymization

### ISSUE THREAD

**Issue by alexmerlin** [dotkernel/frontend-documentation#6]
Document what happens when a user deletes their own account.
Make sure to include the new config value `userAnonymizeAppend` introduced by the PR that fixes https://github.com/dotkernel/frontend/issues/479.

**Comment by bidi47** [comment]
@arhimede, @alexmerlin, would this issue justify an entry under 'Core Features'?

**Comment by alexmerlin** [comment]
> @arhimede, @alexmerlin, would this issue justify an entry under 'Core Features'?

Unless we want to create some new section for privacy-related docs, `Core features` seems to be the most suitable place to me.
